sudo: required
language: node_js
node_js:
  - 11

branches:
  except:
    - develop
    - /^feature/\d+\.\d+$/
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - npm update

install:
  - npm install

script:
  - yarn coveralls

before_deploy:
  - npm --no-git-tag-version version patch

deploy:
  edge: true
  provider: npm
  email: "enesusta@protonmail.com"
  api_key: $NPM_API_KEY
  skip_cleanup: true
